services:
  backend:
    image: next_core_back:latest
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    volumes:
      - /home/pi/Desktop/next_core_blog/wwwroot/files:/source/app/wwwroot/files

  frontend:
    image: next_core_front:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
