# [ Pull official base image ]
FROM node:latest as build

# [ Set work directory ]
WORKDIR /source

# [ Install dependency ]
COPY client-app/package.json ./
COPY client-app/yarn.lock ./

# [ Copy Enviorment key ]
COPY client-app/.env ./

RUN yarn install

# [ Copy Front files ]
COPY client-app/api ./api
COPY client-app/hooks ./hooks
COPY client-app/lib ./lib
COPY client-app/pages ./pages
COPY client-app/public ./public
COPY client-app/store ./store
COPY client-app/styles ./styles
COPY client-app/types ./types
COPY client-app/utils ./utils
COPY client-app/.babelrc ./
COPY client-app/next.config.js ./
COPY client-app/package.json ./
COPY client-app/tsconfig.json ./


# [ Next.js build ]
RUN yarn build
EXPOSE 3000

ENTRYPOINT [ "yarn", "start" ]

