# [ Pull official base image ]
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# [ Set work directory ]
WORKDIR /source

# [ Copy Backend files ]
COPY Controllers/ ./Controllers/
COPY Repository/ ./Repository/
COPY Model/ ./Model/
# File, Security 
COPY CommonLibrary/ ./CommonLibrary/
# DB Dapper ORM 
COPY Context/ ./Context/
# .NET CS Proj 
COPY *.csproj ./
# .NET Solution 
COPY *.sln ./
# .NET Entry Point 
COPY Program.cs ./
# DB ConnectionStrings 
COPY appsettings.json ./

# [ .NET build and release ]
RUN dotnet restore
RUN dotnet dev-certs https --trust
RUN dotnet publish -c release -o ./app 


WORKDIR /source/app

EXPOSE 5001

# Run server
ENTRYPOINT [ "dotnet", "next_core_blog.dll" ]

