name: backend-ssh-deploy
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: backend-deploy
    runs-on: ubuntu-latest

     steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "dotnet build"
        run: dotnet build Next_Core_Blog.csproj

        
    steps:
      - name: Deploy
        run: |
          CMDS=$(cat <<CMD 
              nohup ./backend-server-deploy.sh > nohup.out 2>&1 &
          CMD
          )
          sshpass -p ${{ secrets.FTP_PASSWORD }} \
            ssh -o 'StrictHostKeyChecking no' \
              -p ${{ secrets.PORT }} \
              ${{secrets.FTP_USERNAME}}@${{secrets.FTP_HOST}} \
              -t "$CMDS" \
          && exit
