name: Our First Workflow

on : 
  push: 
    branches: ["main"]
  pull_request:


jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses : actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Print working directory
        run : pwd

      - name: Show list files
        run : ls -al
      
      - name: 'dotnet build'
        run : dotnet build Next_Core_Blog.csproj

      - name: 'ftp file trasmit'
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with: 
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.PORT }}
